import { describe, expect, it } from "vitest";
import { Board, Move, MovePair } from "../src/engine";
import fixtures from "./fixtures/parity.json";

interface Scenario {
  name: string;
  pairs: [string, string][];
  states: Record<string, [number, number]>[];
  winner: number;
  final_html: string;
}

function serializeState(board: Board): Record<string, [number, number]> {
  return Object.fromEntries(
    Object.entries(board.state).map(([name, node]) => [
      name,
      [node.owner, node.troopCount],
    ])
  );
}

// Golden-file regression suite. These fixtures were generated by the original
// Python engine (now archived); they are kept because they exercise long
// multi-round sequences — restock, clamping, full HTML render — that the unit
// tests do not. Regenerate from src/engine.ts if the rules change on purpose —
// `final_html` has been regenerated since (history now renders newest-first),
// so it no longer matches Python byte for byte; the states and winners do.
describe("engine regression fixtures", () => {
  for (const scenario of fixtures as unknown as Scenario[]) {
    it(`replays ${scenario.name} identically`, () => {
      const board = new Board();
      scenario.pairs.forEach(([p1, p2], idx) => {
        board.applyMovePair(new MovePair(new Move(p1), new Move(p2)));
        if ((idx + 1) % 3 === 0) board.restock();
        expect(serializeState(board), `after pair ${idx + 1}`).toEqual(
          scenario.states[idx]
        );
      });
      expect(board.winner).toBe(scenario.winner);
      expect(board.toHtmlTable()).toBe(scenario.final_html);
    });
  }
});
