version: '3.4'

services:
  _base:
    &base
    build:
      dockerfile: Dockerfile
      context: .
    volumes:
      - ./:/code
    ports:
      - 9000:9000

  repl:
    <<: *base
    command: 'clj -M --main cljs.main -w src/squarular/ --repl-opts "{:launch-browser false}" -c squarular.core -r'

  dev:
    <<: *base
    command: bash

  # test:
    # <<: *base
    # command: lein test
