version: '3.4'

services:
  _base:
    &base
    build:
      dockerfile: Dockerfile
      context: .
    volumes:
      - ./:/code

  repl:
    <<: *base
    command: lein repl

  dev:
    <<: *base
    command: bash
    ports:
      - 9000:9000

  # run tests
  test:
    <<: *base
    command: lein test
